name: Deploy Versioned Docs with Mike

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # To fetch tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mike

      - name: Configure Git (for mike to push)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Extract tag version
        id: get_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Deploy version ${{ env.VERSION }}
        run: mike deploy ${{ env.VERSION }} --update docs/${{ env.VERSION }}

      - name: Determine latest tag
        id: latest_tag
        run: |
          latest=$(git tag --sort=-v:refname | head -n 1)
          echo "LATEST_VERSION=$latest" >> $GITHUB_ENV

      - name: Set default version to latest (${{ env.LATEST_VERSION }})
        run: mike set-default ${{ env.LATEST_VERSION }}

      - name: Push to gh-pages
        run: mike push
        
#      - name: Deploy versioned docs with mike
#        run: |
#          TAG_NAME=${GITHUB_REF#refs/tags/}
#          mike deploy --push --update-aliases "$TAG_NAME" latest
